// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorldCupPredictor.API.Data;

#nullable disable

namespace WorldCupPredictor.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622160412_AddGiveaway")]
    partial class AddGiveaway
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorldCupPredictor.API.Models.ActualBest3rdQualifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("ActualBest3rdQualifiers");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Bracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("ShareToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Brackets");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.BracketBest3rdPick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BracketId")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("BracketId", "Rank")
                        .IsUnique();

                    b.ToTable("BracketBest3rdPicks");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.BracketDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSubmittedFinal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PicksJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BracketDrafts");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.BracketGroupPick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BracketId")
                        .HasColumnType("integer");

                    b.Property<int?>("FirstTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondTeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirstTeamId");

                    b.HasIndex("GroupId");

                    b.HasIndex("SecondTeamId");

                    b.HasIndex("BracketId", "GroupId")
                        .IsUnique();

                    b.ToTable("BracketGroupPicks");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.BracketPick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<int>("BracketId")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int?>("PickedTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PickedTeamId");

                    b.HasIndex("BracketId", "MatchId")
                        .IsUnique();

                    b.ToTable("BracketPicks");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.BracketPickLineupPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BracketPickId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("BracketPickId", "PlayerId")
                        .IsUnique();

                    b.ToTable("BracketPickLineupPlayers");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Giveaway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DrawnAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLuckyDraw")
                        .HasColumnType("boolean");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<string>("Prize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("WinnerUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("WinnerUserId");

                    b.ToTable("Giveaways");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.GiveawayEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<int>("GiveawayId")
                        .HasColumnType("integer");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GiveawayId", "UserId")
                        .IsUnique();

                    b.ToTable("GiveawayEntries");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalApiId")
                        .HasColumnType("text");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("MatchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<int?>("SlotNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("WinnerTeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("WinnerTeamId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ShirtNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FifaCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FifaRanking")
                        .HasColumnType("integer");

                    b.Property<string>("FlagUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FlagEmoji");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seeding")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FifaCode")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.TournamentConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BracketLockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TournamentConfigs");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.TournamentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualFirstTeamId")
                        .HasColumnType("integer");

                    b.Property<int?>("ActualSecondTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActualFirstTeamId");

                    b.HasIndex("ActualSecondTeamId");

                    b.ToTable("TournamentGroups");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.UserGroupMember", b =>
                {
                    b.Property<int>("UserGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserGroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroupMembers");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.ActualBest3rdQualifier", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Bracket", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.User", "User")
                        .WithOne("Bracket")
                        .HasForeignKey("WorldCupPredictor.API.Models.Bracket", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.BracketBest3rdPick", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.Bracket", "Bracket")
                        .WithMany("Best3rdPicks")
                        .HasForeignKey("BracketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldCupPredictor.API.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bracket");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.BracketDraft", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.BracketGroupPick", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.Bracket", "Bracket")
                        .WithMany("GroupPicks")
                        .HasForeignKey("BracketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldCupPredictor.API.Models.Team", "FirstTeam")
                        .WithMany()
                        .HasForeignKey("FirstTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorldCupPredictor.API.Models.TournamentGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorldCupPredictor.API.Models.Team", "SecondTeam")
                        .WithMany()
                        .HasForeignKey("SecondTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bracket");

                    b.Navigation("FirstTeam");

                    b.Navigation("Group");

                    b.Navigation("SecondTeam");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.BracketPick", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.Bracket", "Bracket")
                        .WithMany("Picks")
                        .HasForeignKey("BracketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldCupPredictor.API.Models.Match", "Match")
                        .WithMany("BracketPicks")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldCupPredictor.API.Models.Team", "PickedTeam")
                        .WithMany()
                        .HasForeignKey("PickedTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bracket");

                    b.Navigation("Match");

                    b.Navigation("PickedTeam");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.BracketPickLineupPlayer", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.BracketPick", "BracketPick")
                        .WithMany("LineupPlayers")
                        .HasForeignKey("BracketPickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldCupPredictor.API.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BracketPick");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Giveaway", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorldCupPredictor.API.Models.User", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Match");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.GiveawayEntry", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.Giveaway", "Giveaway")
                        .WithMany("Entries")
                        .HasForeignKey("GiveawayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldCupPredictor.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Giveaway");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Match", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorldCupPredictor.API.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorldCupPredictor.API.Models.Team", "WinnerTeam")
                        .WithMany()
                        .HasForeignKey("WinnerTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("WinnerTeam");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Player", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.RefreshToken", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Team", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.TournamentGroup", "Group")
                        .WithMany("Teams")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.TournamentGroup", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.Team", "ActualFirstTeam")
                        .WithMany()
                        .HasForeignKey("ActualFirstTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorldCupPredictor.API.Models.Team", "ActualSecondTeam")
                        .WithMany()
                        .HasForeignKey("ActualSecondTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActualFirstTeam");

                    b.Navigation("ActualSecondTeam");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.UserGroup", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.User", "Owner")
                        .WithMany("OwnedGroups")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.UserGroupMember", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.UserGroup", "UserGroup")
                        .WithMany("Members")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldCupPredictor.API.Models.User", "User")
                        .WithMany("UserGroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Bracket", b =>
                {
                    b.Navigation("Best3rdPicks");

                    b.Navigation("GroupPicks");

                    b.Navigation("Picks");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.BracketPick", b =>
                {
                    b.Navigation("LineupPlayers");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Giveaway", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Match", b =>
                {
                    b.Navigation("BracketPicks");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.TournamentGroup", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.User", b =>
                {
                    b.Navigation("Bracket");

                    b.Navigation("OwnedGroups");

                    b.Navigation("UserGroupMemberships");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.UserGroup", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
